<?php

namespace AppBundle\Repository;

/**
 * WealthByAppraiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WealthByAppraiserRepository extends \Doctrine\ORM\EntityRepository
{
}
