<?php

namespace AppBundle\Repository;

/**
 * WealthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WealthRepository extends \Doctrine\ORM\EntityRepository
{
}
