app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /zaloguj
    defaults: { _controller: AppBundle:Security:login }

# login_check:
#     path:     /login/check
    # defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    path:     /wyloguj
    # defaults: { _controller: AppBundle:Security:logout }

user_index:
    path:     /uzytkownicy
    defaults: { _controller: AppBundle:Security:index }

user_edit:
    path:     /uzytkownik/edytuj/{id}
    defaults: { _controller: AppBundle:Security:edit }
    requirements:
        id:     \d+

user_new:
    path:     /uzytkownik/nowy
    defaults: { _controller: AppBundle:Security:new }

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

lead_index:
    path:     /klienci/{page}
    defaults: { _controller: AppBundle:Lead:index, page: 1 }
    requirements:
        page: \d+

lead_new:
    path:     /klient/nowy
    defaults: { _controller: AppBundle:Lead:new }

lead_edit:
    path:     /klient/{id}/edytuj
    defaults: { _controller: AppBundle:Lead:edit }
    requirements:
        id: \d+

lead_remove:
    path:     /klient/{id}/usun
    defaults: { _controller: AppBundle:Lead:remove }
    requirements:
        id: \d+

lead_credit_index:
    path:     /klient/{id}/kredyty/{page}
    defaults: { _controller: AppBundle:Lead:indexCredit, page: 1  }
    requirements:
        page: \d+

lead_credit_new:
    path:     /klient/{id}/kredyt-nowy
    defaults: { _controller: AppBundle:Lead:newCredit }
    requirements:
        id: \d+

lead_credit_edit:
    path:     /klient/{leadId}/kredyt-edytuj/{creditId}
    defaults: { _controller: AppBundle:Lead:editCredit }
    requirements:
        leadId: \d+
        creditId: \d+

lead_credit_remove:
    path:     /klient/{leadId}/kredyt-usun/{creditId}
    defaults: { _controller: AppBundle:Lead:removeCredit }
    requirements:
        leadId: \d+
        creditId: \d+