app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /zaloguj
    defaults: { _controller: AppBundle:Security:login }

# login_check:
#     path:     /login/check
    # defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    path:     /wyloguj
    # defaults: { _controller: AppBundle:Security:logout }

user_index:
    path:     /uzytkownicy
    defaults: { _controller: AppBundle:Security:index }

user_edit:
    path:     /uzytkownik/edytuj/{id}
    defaults: { _controller: AppBundle:Security:edit }
    requirements:
        id:     \d+

user_new:
    path:     /uzytkownik/nowy
    defaults: { _controller: AppBundle:Security:new }

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

lead_index:
    path:     /klienci
    defaults: { _controller: AppBundle:Lead:index }

lead_new:
    path:     /klient/nowy
    defaults: { _controller: AppBundle:Lead:new }