app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /zaloguj
    defaults: { _controller: AppBundle:Security:login }

# login_check:
#     path:     /login/check
    # defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    path:     /wyloguj
    # defaults: { _controller: AppBundle:Security:logout }

user_index:
    path:     /uzytkownicy
    defaults: { _controller: AppBundle:Security:index }

user_edit:
    path:     /uzytkownik/edytuj/{id}
    defaults: { _controller: AppBundle:Security:edit }
    requirements:
        id:     \d+

user_new:
    path:     /uzytkownik/nowy
    defaults: { _controller: AppBundle:Security:new }
    
user_new_success:
    path:     /uzytkownik/nowy/success/{id}
    defaults: {_controller: AppBundle:Security:success }
    requirements:
        id: \d+

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

lead_index:
    path:     /klienci/{page}
    defaults: { _controller: AppBundle:Lead:index, page: 1 }
    requirements:
        page: \d+

lead_new:
    path:     /klient/nowy
    defaults: { _controller: AppBundle:Lead:new }

lead_edit:
    path:     /klient/{id}/edytuj
    defaults: { _controller: AppBundle:Lead:edit }
    requirements:
        id: \d+

lead_remove:
    path:     /klient/{id}/usun
    defaults: { _controller: AppBundle:Lead:remove }
    requirements:
        id: \d+

credit_index:
    path:     /{type}/{id}/kredyty/{page}
    defaults: { _controller: AppBundle:Credit:index, page: 1  }
    requirements:
        page: \d+
        type: klient|firma

credit_new:
    path:     /{type}/{id}/kredyt-nowy
    defaults: { _controller: AppBundle:Credit:new }
    requirements:
        id: \d+
        type: klient|firma

credit_edit:
    path:     /{type}/{id}/kredyt-edytuj/{creditId}
    defaults: { _controller: AppBundle:Credit:edit }
    requirements:
        id: \d+
        creditId: \d+
        type: klient|firma

credit_remove:
    path:     /{type}/{id}/kredyt-usun/{creditId}
    defaults: { _controller: AppBundle:Credit:remove }
    requirements:
        id: \d+
        creditId: \d+
        type: klient|firma

leasing_index:
    path:     /fimra/{id}/leasing/{page}
    defaults: { _controller: AppBundle:Leasing:index, page: 1  }
    requirements:
        page: \d+

leasing_new:
    path:     /firma/{id}/leasing-nowy
    defaults: { _controller: AppBundle:Leasing:new }
    requirements:
        id: \d+

leasing_edit:
    path:     /firma/{id}/leasing-edytuj/{leasingId}
    defaults: { _controller: AppBundle:Leasing:edit }
    requirements:
        id: \d+
        leasingId: \d+

leasing_remove:
    path:     /firma/{id}/leasing-usun/{leasingId}
    defaults: { _controller: AppBundle:Leasing:remove }
    requirements:
        id: \d+
        leasingId: \d+

wealth_by_appraiser_index:
    path:     /klient/{id}/majatek-rzeczoznawca/{page}
    defaults: { _controller: AppBundle:WealthByAppraiser:index, page: 1  }
    requirements:
        page: \d+

wealth_by_appraiser_new:
    path:     /klient/{id}/majatek-rzeczoznawca/nowy
    defaults: { _controller: AppBundle:WealthByAppraiser:new }
    requirements:
        id: \d+

wealth_by_appraiser_edit:
    path:     /klient/{leadId}/majatek-rzeczoznawca/edytuj/{wealthByAppraiserId}
    defaults: { _controller: AppBundle:WealthByAppraiser:edit }
    requirements:
        leadId: \d+
        wealthByAppraiserId: \d+

wealth_by_appraiser_remove:
    path:     /klient/{leadId}/majatek-rzeczoznawca/usun/{wealthByAppraiserId}
    defaults: { _controller: AppBundle:WealthByAppraiser:remove }
    requirements:
        leadId: \d+
        wealthByAppraiserId: \d+

wealth_index:
    path:     /klient/{id}/majatek/{page}
    defaults: { _controller: AppBundle:Wealth:index, page: 1  }
    requirements:
        page: \d+

wealth_new:
    path:     /klient/{id}/majatek/nowy
    defaults: { _controller: AppBundle:Wealth:new }
    requirements:
        id: \d+

wealth_edit:
    path:     /klient/{leadId}/majatek/edytuj/{wealthId}
    defaults: { _controller: AppBundle:Wealth:edit }
    requirements:
        leadId: \d+
        wealthId: \d+

wealth_remove:
    path:     /klient/{leadId}/majatek/usun/{wealthId}
    defaults: { _controller: AppBundle:Wealth:remove }
    requirements:
        leadId: \d+
        wealthId: \d+

shares_index:
    path:     /klient/{id}/akcje/{page}
    defaults: { _controller: AppBundle:Shares:index, page: 1  }
    requirements:
        page: \d+

shares_new:
    path:     /klient/{id}/akcje/nowy
    defaults: { _controller: AppBundle:Shares:new }
    requirements:
        id: \d+

shares_edit:
    path:     /klient/{leadId}/akcje/edytuj/{sharesId}
    defaults: { _controller: AppBundle:Shares:edit }
    requirements:
        leadId: \d+
        sharesId: \d+

shares_remove:
    path:     /klient/{leadId}/akcje/usun/{sharesId}
    defaults: { _controller: AppBundle:Shares:remove }
    requirements:
        leadId: \d+
        sharesId: \d+

company_index:
    path:     /firmy/{page}
    defaults: { _controller: AppBundle:Company:index, page: 1 }
    requirements:
        page: \d+

company_new:
    path:     /firma/nowy
    defaults: { _controller: AppBundle:Company:new }

company_edit:
    path:     /firma/{id}/edytuj
    defaults: { _controller: AppBundle:Company:edit }
    requirements:
        id: \d+

company_remove:
    path:     /firma/{id}/usun
    defaults: { _controller: AppBundle:Company:remove }
    requirements:
        id: \d+