
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user:
            entity:
                class: AppBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
            # remember_me:
            #     key: '%secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path: /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/zaloguj$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
