AppBundle\Entity\Shares:
  type: entity
  repositoryClass: AppBundle\Repository\SharesRepository
  table: shares
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nameAndType:
      type: string
      length: 64
      nullable: true
    numberOfSharesHeld:
      type: float
      nullable: true
    value:
      type: float
      nullable: true
  manyToOne: 
    lead:
      targetEntity: Lead
      inversedBy: shares
      joinColumn:
        name: shares_id
        referencedColumnName: id