AppBundle\Entity\Wealth:
  type: entity
  repositoryClass: AppBundle\Repository\WealthRepository
  table: wealth
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    type:
      type: string
      length: 64
      nullable: true
    estimatedValuation:
      type: float
      nullable: true
  manyToOne: 
    lead:
      targetEntity: Lead
      inversedBy: wealth
      joinColumn:
        name: wealth_id
        referencedColumnName: id